<?php
$d['package']['menus'] = array(
	array('name'=>'대분류1','id'=>'41','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'1','parent'=>'','is_child'=>'1','gid'=>'1',),
		array('name'=>'중분류1','id'=>'46','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'2','parent'=>'41','is_child'=>'1','gid'=>'1',),
			array('name'=>'소분류1','id'=>'51','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'3','parent'=>'46','is_child'=>'0','gid'=>'1',),
			array('name'=>'소분류2','id'=>'52','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'3','parent'=>'46','is_child'=>'0','gid'=>'2',),
			array('name'=>'소분류3','id'=>'53','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'3','parent'=>'46','is_child'=>'0','gid'=>'3',),
		array('name'=>'중분류2','id'=>'47','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'2','parent'=>'41','is_child'=>'0','gid'=>'2',),
		array('name'=>'중분류3','id'=>'48','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'2','parent'=>'41','is_child'=>'0','gid'=>'3',),
		array('name'=>'중분류4','id'=>'49','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'2','parent'=>'41','is_child'=>'0','gid'=>'4',),
		array('name'=>'중분류5','id'=>'50','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'2','parent'=>'41','is_child'=>'0','gid'=>'5',),
	array('name'=>'대분류2','id'=>'42','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'1','parent'=>'','is_child'=>'1','gid'=>'2',),
		array('name'=>'중분류1','id'=>'54','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'2','parent'=>'42','is_child'=>'0','gid'=>'1',),
		array('name'=>'중분류2','id'=>'55','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'2','parent'=>'42','is_child'=>'0','gid'=>'2',),
		array('name'=>'중분류3','id'=>'56','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'2','parent'=>'42','is_child'=>'0','gid'=>'3',),
	array('name'=>'대분류3','id'=>'43','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'1','parent'=>'','is_child'=>'0','gid'=>'3',),
	array('name'=>'대분류4','id'=>'44','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'1','parent'=>'','is_child'=>'0','gid'=>'4',),
	array('name'=>'대분류5','id'=>'45','menutype'=>'3','mobile'=>'0','target'=>'','redirect'=>'0','joint'=>'','layout'=>'','imghead'=>'','imgfoot'=>'','addattr'=>'','depth'=>'1','parent'=>'','is_child'=>'0','gid'=>'5',),
);
?>
