<?php
//admin.php
$lang['widget-mk-menu-default']['1001'] = 'Are you sure to extract the code of this widget(%s)?'; //이 위젯(<strong>%s</strong>)의 코드를 추출하시겠습니까?
$lang['widget-mk-menu-default']['1002'] = 'Starting Menu'; //시작메뉴
$lang['widget-mk-menu-default']['1003'] = 'Root Path'; //처음(root)
$lang['widget-mk-menu-default']['1004'] = 'Step 1 Selected Menu'; //1단계 선택메뉴
$lang['widget-mk-menu-default']['1005'] = 'Step 2 Selected Menu'; //2단계 선택메뉴
$lang['widget-mk-menu-default']['1006'] = 'Step 3 Selected Menu'; //3단계 선택메뉴
$lang['widget-mk-menu-default']['1007'] = 'Extraction step'; //추출단계
$lang['widget-mk-menu-default']['1008'] = 'Sub %s step of Start Menu'; //시작메뉴 하위 %s단계
$lang['widget-mk-menu-default']['1009'] = 'Link method'; //링크방식
$lang['widget-mk-menu-default']['1010'] = 'Default'; //일반
$lang['widget-mk-menu-default']['1011'] = 'Bookmark'; //북마크
$lang['widget-mk-menu-default']['1012'] = 'If you specify a bookmark way links are created as follows.'; //북마크 방식을 지정하면 링크가 다음과 같이 생성됩니다.
$lang['widget-mk-menu-default']['1013'] = 'Drop down'; //드롭다운
$lang['widget-mk-menu-default']['1014'] = 'The bootstrap class drop-down insertion'; //부트스트랩 드롭다운 class 삽입
$lang['widget-mk-menu-default']['1015'] = 'Top menu link contains in the sub-menu'; //서브메뉴에 상위메뉴 링크를 포함시킴
$lang['widget-mk-menu-default']['1016'] = '(Drop-down menu is supported only step 2.)'; //(드롭다운은 메뉴 2단계까지만 지원됩니다.)
$lang['widget-mk-menu-default']['1017'] = 'The structure of the menu is generated by <code>&lt;ul&gt;</code> tag.'; //메뉴의 구조는 <code>&lt;ul&gt;</code> 태그로 생성됩니다.
$lang['widget-mk-menu-default']['1018'] = 'After wrapping the extracted code in a format such as <code>&lt;ul class=&quot;nav navbar-nav&quot;&gt;[WIDGET-CODE]&lt;/ul&gt;</code> Please design with CSS.'; //추출한 코드를 <code>&lt;ul class=&quot;nav navbar-nav&quot;&gt;[위젯코드]&lt;/ul&gt;</code> 와 같은 형식으로 감싼 후 CSS로 디자인해 주세요.
$lang['widget-mk-menu-default']['1019'] = 'Selected menu is <code> .active </code> can be accessed by the class.'; //선택된 메뉴는 <code>.active</code> 클래스로 접근할 수 있습니다.

//main.php
?>